### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by vuki656** [vuki656/package-info.nvim#15]
- [x] Add a nice readme (steal from [folke](https://github.com/folke/todo-comments.nvim), thanks folke)
- [x] Add image to readme
- [x] Add issue templates
- [x] Add pipeline 
    - [x] Stylua on project
- [ ] Cut a `0.1` release
- [ ] Post on reddit
- [ ] Post on [awesome-neovim](https://github.com/rockerBOO/awesome-neovim)
- [ ] Post in VIM discord
